nestjs/schematics

Makefile
package.json

Schematics v4.0.0-rc2

---

README.md
package.json
src/application/files/test/app.e2e-spec.ts

fix #32 docs(npm): no readme displayed on npm.org

Schematics v4 documentation

---

README.md
package.json

fix #32 docs(npm): no readme displayed on npm.org

Schematics v5 documentation

---

package.json
src/collection.json
src/configuration/factory.ts
src/configuration/files/.nestcli.json
src/configuration/schema.d.ts
test/configuration/factory.test.ts

feature(configuration) : generate cli configuration file

---

package.json
src/collection.json
src/provider/factory.ts
src/provider/files/__name__.provider.ts
src/provider/files/__name__.ts
src/provider/schema.d.ts
src/utils/module-import.declarator.ts
src/utils/module.declarator.ts
test/provider/factory.test.ts
test/utils/module-import.declarator.test.ts
test/utils/module.declarator.test.ts

fix #38 feature(provider) : manage provider schematics

feature(provider) : manage provider

---

src/application/files/ts/package.json

Use Nest v5.0.0-beta.6 and RxJS v6.0.0.

fix(application): update dependencies

---

src/application/files/ts/src/app.controller.spec.ts

fix(test) : add missing service import in controller spec

---

package-lock.json
package.json
src/application/files/ts/package.json
src/application/files/ts/src/app.controller.spec.ts
src/utils/metadata.manager.ts
src/utils/module-metadata.declarator.ts
test/controller/factory.test.ts
test/module/factory.test.ts
test/provider/factory.test.ts
test/service/factory.test.ts
test/utils/metadata.manager.test.ts
test/utils/module-metadata.declarator.test.ts
test/utils/module.declarator.test.ts

V5 patches and features

---

src/middleware/files/ts/__name__.middleware.ts
test/middleware/factory.test.ts

Modified FunctionMiddleware by MiddlewareFunction in name.middleware.ts and middleware/factory.test.ts.

fix() : fix middleware ts file import and middleware test

---

package.json
src/application/files/ts/package.json

Init new nest project with nest v5 instead of nest v5 beta.6

---

src/utils/module.finder.ts
test/service/factory.test.ts
test/utils/module.finder.test.ts

This will fix service / provider module declaration when generate

fix() : service / provider module declaration

---

src/application/files/js/src/app.controller.js
src/application/files/ts/src/app.module.ts
src/filter/files/js/__name__.filter.js
src/filter/files/ts/__name__.filter.ts
src/gateway/files/js/__name__.gateway.js
src/gateway/files/ts/__name__.gateway.ts
src/guard/files/js/__name__.guard.js
src/guard/files/ts/__name__.guard.ts
src/interceptor/files/js/__name__.interceptor.js
src/interceptor/files/ts/__name__.interceptor.ts
src/middleware/files/js/__name__.middleware.js
src/middleware/files/ts/__name__.middleware.ts
src/pipe/files/ts/__name__.pipe.ts
test/controller/factory.test.ts
test/filter/factory.test.ts
test/gateway/factory.test.ts
test/guard/factory.test.ts
test/interceptor/factory.test.ts
test/middleware/factory.test.ts
test/module/factory.test.ts
test/pipe/factory.test.ts
test/provider/factory.test.ts
test/service/factory.test.ts

I spent some time trying to adjust default templates to the best practices

feature() : adjust templates to the best practices

---

src/templates/ts/application/test/app.e2e-spec.ts

src/app.module has no exported member 'ApplicationModule'.

fix(schematics): AppModule not ApplicationModule

---

Dockerfile
src/lib/factories/application.factory.ts
src/lib/factories/application.schema.d.ts
src/templates/js/application/README.md
src/templates/js/application/test/app.e2e-spec.js
src/templates/ts/application/README.md
src/templates/ts/application/src/app.module.ts
src/templates/ts/application/test/app.e2e-spec.ts
test/lib/factories/controller.factory.test.ts
test/lib/factories/module.factory.test.ts
test/lib/factories/provider.factory.test.ts
test/lib/factories/service.factory.test.ts

feature(documentation) : set used package manager in README.md file

---

src/utils/metadata.manager.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fixing bug length of null

---

src/lib/application/application.factory.test.ts
src/lib/application/application.schema.d.ts
src/lib/application/files/js/src/main.js
src/lib/application/files/ts/src/main.ts
src/lib/application/schema.json

```
[ ] Bugfix
[x] Feature
```
Nest js generated without clusters
I added a new option ```cluster``` that allows to create an application in a cluster.
```
[ ] Yes
[x] No
```

Feat(application) add

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: Remove Gitter badge

---

src/lib/application/files/js/package.json
src/lib/application/files/ts/package.json

- [x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
```
[X ] Bugfix
[ ] Feature
```
Issue Number: Closes #181 
Jest will look into the src and libs folder for the test files.
```
[ ] Yes
[ ] No
```

chore: update jest config to support src and libs folder

---

package.json
src/lib/application/files/js/.babelrc
src/lib/application/files/js/package.json
src/lib/application/files/ts/package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat() use cli scipts, update dependencies

---

src/lib/application/files/js/.gitignore
src/lib/application/files/ts/.gitignore

Add .env to .gitignore

---

src/lib/application/files/ts/test/app.e2e-spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Added missing type information in app.e2e-spec.ts.
In the current source code, the type of app is any.
```
[ ] Yes
[x] No
```

test(e2e): Adding correct type information to E2E spec example

---

src/lib/class/class.factory.test.ts
src/lib/class/class.factory.ts
src/lib/class/class.schema.d.ts
src/lib/class/files/js/__name__.js
src/lib/class/files/js/__name__.spec.js
src/lib/class/files/ts/__name__.spec.ts
src/lib/class/files/ts/__name__.ts
src/lib/class/schema.json

```
[ ] Bugfix
[x] Feature
```
Issue Number: #123 
The classes with "." will be generated without "."
User.Entity will generate class user-entity.ts and class name as UserEntity
```
[ ] Yes
[x] No
```

feat: generate class with suffix

---

src/lib/application/application.factory.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest-cli/issues/222
```
[ ] Yes
[x] No
```

fix(application.factory): package name

---

src/lib/application/files/js/package.json
src/lib/application/files/ts/package.json

- ↑ I feel we don't have to do it for this chore.
- ↑ Same, it might not required for this.
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Issue Number: #307
- Set package.json private by `nest new`.
```
[ ] Yes
[x] No
```

chore(license): private package.json

---

CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
N/A
```
[ ] Yes
[x] No
```
This PR, added doc for contributing

docs(contributing): added doc for contributing

---

README.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
N/A
```
[ ] Yes
[x] No
```
This PR, added license on readme

docs(readme): added license on readme

---

src/lib/application/application.schema.d.ts
src/lib/application/files/ts/tsconfig.json
src/lib/application/schema.json

```
[ ] Bugfix
[x] Feature
```
Issue Number: #597 _(only the first step)_
As of the first part to address the issue #597 this PR adds the `strict` option into the `application` schematic.
```
[ ] Yes
[x] No
```
I didn't request to work on the issue #597 but I already know what to do in https://github.com/nestjs/nest-cli after if this PR is merged, and finally closes that issue :)

feat: add `strict` option to application schematic

---

src/collection.json

Issue Number: https://github.com/nestjs/schematics/issues/935
Schematics can be now generated using aliases

feat(schematics-aliases): add aliases for the schematics collection

---

src/lib/application/application.schema.d.ts

A minor update on type definitions to align with what `@nestjs/cli` support
I'm not sure if it's better to change that type to `string` instead, as `packageManager` values are defined by `@nestjs/cli`.

feat: update `ApplicationOptions` typing for `packageManager`

---

src/lib/application/files/ts/README.md

Proposal: When scaffolding the NestJS application, only the logo is generated in the README. What do you think?
(see screenshot)

chore(): update logo readme application

---

src/lib/application/files/ts/.eslintrc.js

Issue Number: https://github.com/nestjs/nest/issues/9430
Added `parserOptions.tsconfigRootDir` to .eslintrc.js
This PR, updated parser options in .eslintrc.js(see issue [here](https://github.com/nestjs/nest/issues/9430))

chore(): updated parser options in .eslintrc.js

---

src/collection.json

Proposal:
Added alias `ìtf` for interface and renamed alias `int ` in `itc` for interceptor

chore(): added alias for interface and rename alias interceptor

---

package-lock.json
package.json
src/lib/sub-app/sub-app.factory.ts

schematics depend on the `fs-extra` package but it is only used in one place and can be replaced.
- dependency `fs-extra` is removed
- devDependency `@types/fs-extra` is removed

refactor: remove dependency fs-extra

---

.circleci/config.yml
package-lock.json
package.json
src/lib/application/files/js/package.json
src/lib/application/files/ts/package.json
src/lib/application/files/ts/tsconfig.json
src/lib/library/files/js/jsconfig.json
src/lib/sub-app/files/js/jsconfig.json
src/lib/sub-app/sub-app.factory.ts
src/lib/sub-app/workspace/js/jsconfig.json
tools/gulp/tsconfig.json
tsconfig.json
tsconfig.lib.json

chore: laying the grounds for 10.0.0

---

src/lib/configuration/configuration.factory.test.ts
src/lib/configuration/configuration.factory.ts
src/lib/configuration/configuration.schema.d.ts

Issue Number: closes https://github.com/nestjs/nest-cli/issues/2207
from `@nestjs/cli` we can use `nest g configuration` without using the monorepo mode.

feat(lib): support undefined project for 'configuration' schematic

---

src/lib/application/files/js/src/main.js
src/lib/application/files/ts/src/main.ts
src/lib/sub-app/files/js/src/main.js
src/lib/sub-app/files/ts/src/main.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #125
```
[ ] Yes
[x] No
```

feat: Use PORT environment variable as default port

---

src/lib/service/service.factory.ts

refactor: drop deprecate nodejs utility api

---

package-lock.json
package.json

Reverts nestjs/schematics#2094

Revert "fix(deps): update angular-cli monorepo to v20 (major)"
