- src/application/files/test/app.e2e-spec.ts
Let me know if this is the wrong branch to PR against, I can see you have a couple RC versions on the go. Maybe it's even been fixed but right now the e2e can't run because the test file tries to import `AppModule` as opposed to `ApplicationModule`
> Fixed a bug in the e2e app test where it referenced the wrong module

- .npmignore
The current `.npmignore` prevents the publication of any of the `.gitignore` files contained in the templates.
Adding a `/` at the beginning of a rule in `.npmignore` (as in `.gitignore`) restricts the rule to the root level and allows the templates to be published including the `.gitignore` files.
> Allows npm to publish gitignore

- src/templates/ts/application/nodemon-debug.json
Debug breaks when using aliased paths
> Add require for tsconfig-paths/register

- src/lib/application/files/js/jsconfig.json
- src/lib/application/files/ts/tsconfig.json
```
[x] Bugfix
[ ] Feature
```
VSCode auto import always show intellisense or automatically import from the `dist` folder 
Auto import of missing imports and intellisense is ignoring `dist` folder
```
[ ] Yes
[x] No
```
related to https://github.com/Microsoft/vscode/issues/40248
> fix: ignore dist folder for better auto importing intellisense

- package-lock.json
- package.json
```
[x] Bugfix
[ ] Feature
```
Typescript is added as dependency and devDpendecny both, which generates warning.
```
[ ] Yes
[x] No
```
> fix: remove typescript as dev dependency

- src/utils/module-import.declarator.ts
- test/utils/module-import.declarator.test.ts
Also, changes the algorithm to insert generated import stamtement
via Array#splice instead of using concat on multiple arrays.
```
[x] Bugfix
[ ] Feature
```
Issue Number: #204 
No new behavior is introduced. Instead, the previously intended behavior of allowing for multi-line imports is now supported.
```
[ ] Yes
[x] No
```
> Matches on "from" instead of "import" to avoid breakage of multi-line imports

- src/lib/application/application.factory.test.ts
- src/lib/application/application.factory.ts
- src/lib/application/application.schema.d.ts
- src/lib/application/schema.json
nestjs/nest-cli#283
```
[ ] Bugfix
[x] Feature
```
Issue Number: nestjs/nest-cli#283
```
> nest new @scope/package
```
This command will generate application files inside the 'package' folder and additionally, it will put everything inside a wrapping folder '@scope'. Furthermore currently there is no option to generate the application to another directory than the same as the application name says.
```
> nest new @scope/package --directory=scope-package
```
This command will produce new application …
> feat(): add directory option to the application schematic

- src/lib/client-app/angular/angular.factory.ts
- (n/a) Tests for the changes have been added (for bug fixes / features)
- (n/a) Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
Schematic fails when using CLI to generate a new Angular app (see: [#337](https://github.com/nestjs/schematics/issues/337#issue-589604381)):
```
➜  nest-monorepo-example git:(master) ✗ nest generate ng-app angular                                
? Would you like to initialize Angular application? Yes
? Would you like to add Angular …
```
> fix(): redress deprecated method in `angular-app` schematic

- src/lib/resource/files/ts/dto/update-__name@singular__.input.ts
- src/lib/resource/resource.factory.test.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #484 
Importing `PartialType` from the `@nestjs/graphql` package, for the graphql scaffolding.
```
[ ] Yes
[x] No
```
> fix(resource): Importing PartialType from the wrong package for graphql

- src/lib/application/files/ts/package.json
```
[x] Bugfix
[ ] Feature
```
The unit test file pattern includes any files containing `test` and the `ts` suffix, since `testRegex: .spec.ts` a regex and not a glob pattern.
Issue Number: #5293 
The test file pattern strictly follows the .spec.ts file suffix. This rules out .e2e-spec.ts files from unit tests.
```
[ ] Yes
[x] No
```
> fix: stricten unit test file pattern

- src/lib/class/schema.json
- src/lib/controller/schema.json
- src/lib/decorator/schema.json
- src/lib/filter/schema.json
- src/lib/gateway/schema.json
- src/lib/guard/schema.json
- src/lib/interceptor/schema.json
- src/lib/interface/schema.json
- src/lib/middleware/schema.json
- src/lib/module/schema.json
- src/lib/pipe/schema.json
- src/lib/provider/schema.json
- src/lib/resolver/schema.json
- src/lib/resource/schema.json
- src/lib/service/schema.json
```
[ ] Bugfix
[x] Feature
```
Currently when using the angular console plugin from nrwl some parameters for the resource schematic show up as text fields, even though they are boolean values.
Issue Number: 561
Schematic fields show up correctly in angular-console plugin
```
[ ] Yes
[x] No
```
> chore(): adding missing types to resource schematic

- src/lib/resource/files/ts/__name__.controller.ts
- src/lib/resource/resource.factory.test.ts
Using `generate resource` creates an `update()` function annotated with `@Put()`. As of my understanding of REST API's `PUT` is meant to replace a full object or create one if it is not existing. But the created function clearly updates only specific values and integrates validation by use of `PartialType()`. Therefor, imo, `@Patch()` should be used instead which is meant to update only specific values of an existing object.
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```
```
[ ] Yes
[X] No
```
> `g resource` may use @Patch() in favor of @Put()

- src/lib/library/library.factory.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: #750 
```
[ ] Yes
[x] No
```
The first commit fixes the problem addressed in the issue. The second commit makes the generated moduleNameMapper entries more clear by only adding one entry per library. 
The fixed original generated entry would be: 
```json
"moduleNameMapper": {
"^@app/my-lib$": "<rootDir>/libs/my-lib/src",
"^@app/my-lib/(.*)$": "<rootDir>/libs/my-lib/src/$1",
}
```
The new generated entry instead is:
```json
"moduleNameMapper": { …
```
> Module name mapper regex

- src/lib/sub-app/files/ts/test/app.e2e-spec.ts
```
[ x] Bugfix
[ ] Feature
```
This was capitalizing the module name when importing e2e tests when generating a new app in the monorepo scheme throwing invalid path error.
no errors with importing modules when creating a new sub-app.
```
[ ] Yes
[x ] No
```
> fix: remove classify for module import

- package-lock.json
- package.json
- src/lib/library/library.factory.ts
- src/lib/sub-app/sub-app.factory.ts
```
[x] Bugfix
[ ] Feature
```
When attempting to use this package with Node `lts/gallium` (`16.x`), an "unsupported engine" warning appears with `@angular-devkit/core`. This warning appears to be due to a version issue with NPM v8. Despite the warning, everything appears to work correctly using that node version.
WhiteSource Renovate's bot attempted to [open a PR updating to version 13](https://github.com/nestjs/schematics/pull/838), but CircleCI is failing at the build stage because that release …
> fix(deps): update angular-cli monorepo to v13 (major)

- .eslintrc.js
- src/lib/application/application.factory.ts
- src/lib/library/library.factory.ts
- src/lib/sub-app/sub-app.factory.ts
- src/utils/metadata.manager.ts
When you run `npm run lint` there is an error.
After the error got fixed there were some lint errors so they are fixed as well.
```
Error
npm run lint
> @nestjs/schematics@8.0.7 lint
> eslint '{src,test}/**/*.ts' --fix
Oops! Something went wrong! :(
ESLint: 8.10.0
Error: Cannot read config file: /home/zlatin/code/experiments/schematics/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /home/zlatin/code/experiments/schematics/.eslintrc.js
at Object.<anonymous> …
```
> Fix npm run lint command

- src/lib/application/files/js/nest-cli.json
- src/lib/application/files/ts/nest-cli.json
- src/lib/configuration/configuration.factory.test.ts
- src/lib/configuration/files/js/nest-cli.json
- src/lib/configuration/files/ts/nest-cli.json
The schema URL was taken from here: https://www.schemastore.org/json and was reviewed here: https://github.com/SchemaStore/schemastore/pull/1947
This is just to help devs on building the `nest-cli.json` file in their IDE/code editor. We'll get no errors if some field is not allowed but we'll get autocompletion for the ones that are allowed
> feat: add `$schema` entry on generated `nest-cli.json` files

- src/lib/application/application.factory.test.ts
- src/lib/application/application.factory.ts
- src/lib/application/application.schema.d.ts
- src/lib/application/schema.json
https://github.com/nestjs/nest-cli/issues/1519
Issue Number: 1519
You can generate project using numbers only.
> feat: Add option to generate project using numbers

- CONTRIBUTING.md
- src/utils/metadata.manager.ts
- test/utils/metadata.manager.test.ts
Issue Number: closes https://github.com/nestjs/nest-cli/issues/1639
now we can have a module declaration like the following:
```ts
@Module({
imports: [
FooModule, // <<
],
})
export class AppModule {}
```
and `nest g module bar` will turn that into:
```ts
import { BarModule } from './bar/bar.module';
@Module({
imports: [
FooModule,
BarModule, // <<
],
})
export class AppModule {}
```
<details>
<summary>Other examples</summary>
```ts
// FROM this:
@Module({
imports: [
FooModule
],
})
export class AppModule {}
// TO this:
@Module({
imports: [
FooModule,
BarModule
],
})
export class AppModule {}
```
```ts
// FROM this:
@Module({
imports: [
FooModule, // <<
],
})
export class AppModule {} …
```
> fix(utils): when imports list has no indentation

- package-lock.json
- package.json
- [ x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ x ] Build related changes
After a fresh installation from CLI and run the lint script the ESLint warning message is displayed saying: 
````
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.8.0
YOUR TYPESCRIPT VERSION: 4.8.2
Please only submit bug reports when using the officially supported version.
=============
````
The linter doesn't work correctly
Issue Number: …
> build(dependency): downgrade typescript version

- src/lib/sub-app/sub-app.factory.ts
If using sub apps inside a monorepo running `npm run build` or `nest build <app_name>` puts the build files inside the path `dist/apps/<app_name>`.
However, the `npm run start:prod` script still points to `dist/main` - the old location before the project became a monorepo.
`npm run start:prod` now points to `dist/apps/<app_name>/main`
N/A
> fix: use correct path in `start:prod` script with sub apps

- src/lib/application/files/ts/nest-cli.json
- src/lib/application/files/ts/package.json
As mentioned here: https://github.com/nestjs/typescript-starter/pull/242 nestjs apps created by `nest new` have the dev. dependency `rimraf` due to the npm-script `prebuild`
But people might not want that npm-script neither that dependency on their projects
As NestJS's CLI have the auto-delete output dir feature (which uses `rimraf` under the hood), I don't see any advantages on having that npm-script on user-land.
> feat: use auto-delete output dir feature from nestjs cli

- .circleci/config.yml
Many pull requests to update dependencies is failed to build caused by Node.js version mismatch.
https://app.circleci.com/pipelines/github/nestjs/schematics/4206/workflows/cca4a55a-054e-48df-986f-5f23d177ac9c/jobs/8186
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@9.1.2
npm ERR! notsup Not compatible with your version of node/npm: npm@9.1.2
npm ERR! notsup Required: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"}
npm ERR! notsup Actual:   {"npm":"8.11.0","node":"v17.9.1"}
npm ERR! A complete log of this run can be …
```
> ci: use nodejs v18

- src/lib/sub-app/sub-app.factory.ts
Dry run for the sub-app generator was
creating new directories stracture anyway.
Closes nestjs/schematics#1234
Issue Number: nestjs/schematics#1234
Using `nest g -d app my-app` doesn't introduce any changes to the files
> fix(sub-app): dry-run

- src/utils/metadata.manager.ts
- src/utils/module-metadata.declarator.ts
- test/utils/metadata.manager.test.ts
Issue Number: closes #1444 
if there's no uncomment occurrence of `@Module`, only the import statement will be added:
> fix(utils): when updating a non-existing nestjs module

- src/lib/resource/files/ts/__name__.module.ts
- src/lib/resource/resource.factory.test.ts
Fixes #1458; see issue for description
Resource module files now include a trailing comma for the object argument passed into `@Module()`
None
> fix: add trailing commas to resource schematic

- src/lib/sub-app/sub-app.factory.ts
Issue Number: closes #1492
given this project:
(note that we have the 'test' folder just to see what's the happy path)
running `npx nest g app qux` will perform the following operations:
we are deleting every file within the directories that will be moved ('src' and 'test')
now that same command will do this instead:
- only 2 _delete_ operations, one for each folder being deleted
- ignore if the folder does not exists
---
when there is no 'test' folder in the project, we'd see:
> fix: when generating app with no 'test'/'src' folder to move

- src/lib/library/library.factory.ts
- src/lib/library/schema.json
- src/lib/readers/file-system.reader.ts
- src/lib/readers/index.ts
- src/lib/readers/reader.ts
- test/lib/readers/file-system.reader.spec.ts
Issue Number: #1562 
if defaultLibraryPrefix key exists, use this prefix first.
```
{
...
"monorepo": true,
"defaultLibraryPrefix": "@my-company"
}
```
I wanna change x-prompt message dynamically, but there is no way to make it dynamically for now.
so I have changed the message, but I think the message is not that good.
let me advise.
It is my first time to contribute to nestjs/schematics, You can give me any feedback, it's all welcome.
> feat: use default library prefix

- src/utils/formatting.ts
- src/utils/index.ts
- test/utils/formatting.test.ts
I just realized that I didn't have a code covered by unit tests and identified a possible bug
> fix: fix formatting when add spacing at the beginning and/end

- src/utils/metadata.manager.ts
when running `nest generate controller` when our `app.module.ts` has any decorator factory before `@Module()`, the wrong decorator is being changed
```ts
import { Injectable, Module, Scope } from '@nestjs/common'
@Injectable({}) // BUG: this will receive the `controllers` prop after nest generate
class Service {}
@Module({
imports: [],
providers: [Service],
controllers: [],
})
export class 
```
[demo-issue-nestjs-cli.webm](https://github.com/nestjs/schematics/assets/13461315/47d96c66-8202-4b22-b03e-511b9863c0cd)
1. we can now have any sort of decorators on `.module.ts` files but only the first `@Module({})` occurrence will be update (if found)
2. minor optimization regarding the …
> fix: when finding the `@Module()` decorator occurrence

- src/lib/application/files/ts/tsconfig.json
as per https://github.com/nestjs/typescript-starter/pull/311/
> feat: enable `forceConsistentCasingInFileNames` for 'application' template

- src/lib/application/files/ts/tsconfig.json
Reverts nestjs/schematics#1899
> Revert "feat: enable `forceConsistentCasingInFileNames` for 'application' template"

- src/lib/application/files/ts/package.json
Issue Number: closes https://github.com/nestjs/nest/issues/14092
no errors on running `npm run lint` on a brand new nestjs project
until we migrate the eslint config to their new format, we cannot use `eslint@9`
> fix: downgrade eslint to v8 on application files

- src/lib/library/library.factory.test.ts
- src/lib/library/library.factory.ts
- src/lib/sub-app/sub-app.factory.test.ts
- src/lib/sub-app/sub-app.factory.ts
- src/utils/index.ts
- src/utils/object-sorting.ts
- test/utils/object-sorting.test.ts
Issue Number: #1956
Sort library name and sub app names in:
- `projects` of the `nest-cli.json`
- `compilerOptions.path` of the `tsconfig.json`
- `jest.moduleNameMapper` of the `package.json`
to reduce git merge conflicts
> feat: sort library and sub-app names to reduce git merge conflicts

- src/lib/application/files/ts/tsconfig.json
- src/lib/library/files/js/jsconfig.json
- src/lib/sub-app/files/js/jsconfig.json
- src/lib/sub-app/workspace/js/jsconfig.json
- tools/gulp/tsconfig.json
- tsconfig.json
- tsconfig.lib.json
Since NestJS 11 now requires Node.js v20 or higher, Typescript compiler target can be set to ES2023 safely.
(https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping)
This enables usage of new features such as:
- Error cause property
- Array functions: at, findLast, findLastIndex, toSorted...
- Object.hasOwn function
etc...
> chore: update typescript compiler target to ES2023

- src/lib/application/files/ts/package.json
This PR removes SWC-related dependencies (@swc/cli, @swc/core) from the default project template as they're included but not configured, causing confusion and increasing the package size unnecessarily.
Default NestJS project template includes unused SWC dependencies (`@swc/cli`, `@swc/core`) that aren't configured in the project.
Issue Number: #2073 
Removed unused SWC dependencies from the TypeScript project template.
> fix: remove unused `swc` dependencies from `ts` project template #2073

- src/lib/library/library.factory.test.ts
- src/lib/library/library.factory.ts
- src/utils/index.ts
- src/utils/jest-module-mapper.ts
Issue Number: https://github.com/nestjs/nest-cli/issues/3144
When creating a library, `package.json` and `test/jest-e2e.json` generate different moduleNameMapper formats:
- package.json: `^@app/hello(|/.*)$` → `<rootDir>/libs/hello/src/$1`
- jest-e2e.json: `@app/hello/(.*)` and `@app/hello` → `<rootDir>/../libs/hello/src/$1`
This inconsistency causes e2e tests to fail when importing enum exports from libraries.
Both `package.json` and `jest-e2e.json` now use the consistent `^packageKey(|/.*)$` format:
- package.json: `^@app/hello(|/.*)$` → `<rootDir>/libs/hello/src/$1`
- jest-e2e.json: `^@app/hello(|/.*)$` → `<rootDir>/../libs/hello/src/$1`
Added unified `createModuleNameMapper` …
> fix: unify modulenamemapper format consistency
